//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livro.View.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivrosVendidos
    {
        public int ID { get; set; }
        public int IDVenda { get; set; }
        public int IDLivro { get; set; }
    
        public virtual Livro Livro { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
