//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livro()
        {
            this.LivrosVendidos = new HashSet<LivrosVendidos>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public int Genero { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public bool Situation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LivrosVendidos> LivrosVendidos { get; set; }
    }
}
